- id: flynt
  name: flynt
  description: "flynt: string formatting converter"
  entry: flynt
  args: [--fail-on-change]
  language: python
  language_version: python3
  require_serial: true
  types: [python]
