repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'e05c5c0818279e5ac248ac9e954431ba58865e61'  # frozen: v0.15.7
    hooks:
      - id: ruff-format
        exclude: test/integration/(actual|expected|samples).*
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        exclude: test/integration/(actual|expected|samples).*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell  # See pyproject.toml for args
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: test/integration/(actual|expected|samples).*
