//! Differential tests: the Rust port must reproduce flynt 1.0.6's Python
//! helpers byte-for-byte. Fixtures are generated by
//! `tests/fixtures/gen_fixtures.py` from flynt itself + the integration corpus.

use std::collections::HashMap;
use std::path::PathBuf;

use flynt_rs::astutils::{
    apply_unicode_escape_map, ast_to_string, contains_comment, fixup_transformed, parse_expr,
    stdlib_parse, str_in_str, unicode_escape_map,
};
use flynt_rs::quotes::{get_quote_type, get_string_prefix, set_quote_type, QuoteType};
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap()
}

fn quote_name(qt: QuoteType) -> &'static str {
    match qt {
        QuoteType::Single => "single",
        QuoteType::Double => "double",
        QuoteType::TripleSingle => "triple_single",
        QuoteType::TripleDouble => "triple_double",
    }
}

fn quote_from_name(name: &str) -> QuoteType {
    match name {
        "single" => QuoteType::Single,
        "double" => QuoteType::Double,
        "triple_single" => QuoteType::TripleSingle,
        "triple_double" => QuoteType::TripleDouble,
        other => panic!("unknown quote name {other}"),
    }
}

#[test]
fn quotes_match_flynt() {
    let data = fixture("quotes.json");
    let mut n = 0;
    for entry in data.as_array().unwrap() {
        let code = entry["code"].as_str().unwrap();
        assert_eq!(
            get_string_prefix(code),
            entry["prefix"].as_str().unwrap(),
            "prefix mismatch for {code:?}"
        );
        let qt = get_quote_type(code).unwrap_or_else(|e| panic!("get_quote_type({code:?}): {e}"));
        assert_eq!(
            quote_name(qt),
            entry["quote_type"].as_str().unwrap(),
            "quote_type mismatch for {code:?}"
        );
        for (name, expected) in entry["set"].as_object().unwrap() {
            let got = set_quote_type(code, quote_from_name(name));
            assert_eq!(
                &got,
                expected.as_str().unwrap(),
                "set_quote_type({code:?}, {name}) mismatch"
            );
        }
        n += 1;
    }
    assert!(n > 100, "expected a substantial corpus, got {n}");
}

#[test]
fn unparse_matches_flynt() {
    // Byte-for-byte equality with CPython ast.unparse (via flynt's
    // ast_to_string), including the f-string outer delimiter, which follows
    // CPython's avoid-escape preference over ', ", \"\"\", '''.
    let data = fixture("unparse.json");
    let mut failures = Vec::new();
    let mut n = 0;
    for entry in data.as_array().unwrap() {
        let src = entry["src"].as_str().unwrap();
        let expected = entry["expected"].as_str().unwrap();
        let node = match parse_expr(src) {
            Ok(node) => node,
            Err(e) => {
                failures.push(format!("PARSE {src:?}: {e}"));
                continue;
            }
        };
        match ast_to_string(&node) {
            Ok(got) if got == expected => {}
            Ok(got) => {
                failures.push(format!("src={src:?}\n  expected={expected:?}\n  got     ={got:?}"))
            }
            Err(e) => failures.push(format!("ERR {src:?}: {e}")),
        }
        n += 1;
    }
    if !failures.is_empty() {
        panic!(
            "{} / {} unparse mismatches:\n{}",
            failures.len(),
            n,
            failures.join("\n")
        );
    }
}

#[test]
fn fixup_matches_flynt() {
    // The end-to-end contract that governs golden output: fixup_transformed must
    // reproduce flynt byte-for-byte (this is where the outer delimiter is fixed).
    let data = fixture("fixup.json");
    let mut failures = Vec::new();
    let mut n = 0;
    for entry in data.as_array().unwrap() {
        let src = entry["src"].as_str().unwrap();
        let expected = entry["result"].as_str().unwrap();
        let qt = entry["quote_type"].as_str().map(quote_from_name);
        let node = match parse_expr(src) {
            Ok(node) => node,
            Err(_) => continue,
        };
        match fixup_transformed(node, qt) {
            Ok(got) if got == expected => {}
            Ok(got) => failures.push(format!(
                "src={src:?} qt={qt:?}\n  expected={expected:?}\n  got     ={got:?}"
            )),
            Err(e) => failures.push(format!("ERR {src:?} qt={qt:?}: {e}")),
        }
        n += 1;
    }
    assert!(
        failures.is_empty(),
        "{} / {} fixup_transformed mismatches:\n{}",
        failures.len(),
        n,
        failures.join("\n")
    );
}

#[test]
fn str_in_str_matches_flynt() {
    let data = fixture("str_in_str.json");
    let mut failures = Vec::new();
    for entry in data.as_array().unwrap() {
        let src = entry["src"].as_str().unwrap();
        let expected = entry["result"].as_bool().unwrap();
        let node = match parse_expr(src) {
            Ok(n) => n,
            Err(_) => continue,
        };
        let got = str_in_str(&node);
        if got != expected {
            failures.push(format!("src={src:?} expected={expected} got={got}"));
        }
    }
    assert!(failures.is_empty(), "str_in_str mismatches:\n{}", failures.join("\n"));
}

#[test]
fn contains_comment_matches_flynt() {
    let data = fixture("contains_comment.json");
    for entry in data.as_array().unwrap() {
        let code = entry["code"].as_str().unwrap();
        let expected = entry["result"].as_bool().unwrap();
        assert_eq!(contains_comment(code), expected, "contains_comment({code:?})");
    }
}

#[test]
fn stdlib_parse_matches_flynt() {
    // Faithful port of `string.Formatter().parse` — the .format()-call transform
    // (task #6) depends on this byte-for-byte.
    let data = fixture("stdlib_parse.json");
    let mut failures = Vec::new();
    for entry in data.as_array().unwrap() {
        let src = entry["src"].as_str().unwrap();
        let expected = entry["fields"].as_array().unwrap();
        let got = stdlib_parse(src);
        if got.len() != expected.len() {
            failures.push(format!("{src:?}: len {} != {}", got.len(), expected.len()));
            continue;
        }
        for (g, e) in got.iter().zip(expected) {
            let e = e.as_array().unwrap();
            let e_literal = e[0].as_str().unwrap();
            let e_field = e[1].as_str();
            let e_spec = e[2].as_str();
            let e_conv = e[3].as_str();
            let ok = g.literal == e_literal
                && g.field_name.as_deref() == e_field
                && g.format_spec.as_deref() == e_spec
                && g.conversion.map(|c| c.to_string()).as_deref() == e_conv;
            if !ok {
                failures.push(format!("{src:?}: {g:?} != {e:?}"));
            }
        }
    }
    assert!(failures.is_empty(), "stdlib_parse mismatches:\n{}", failures.join("\n"));
}

#[test]
fn unicode_escape_matches_flynt() {
    let data = fixture("escape.json");
    for entry in data.as_array().unwrap() {
        let literal = entry["literal"].as_str().unwrap();
        let got_map = unicode_escape_map(literal).unwrap();

        // Compare map char -> [escapes].
        let expected_map = entry["map"].as_object().unwrap();
        let got_as_json: HashMap<String, Vec<String>> = got_map.clone();
        assert_eq!(
            got_as_json.len(),
            expected_map.len(),
            "map size mismatch for {literal:?}: got {got_as_json:?}"
        );
        for (ch, escapes) in expected_map {
            let expected: Vec<String> = escapes
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_str().unwrap().to_string())
                .collect();
            assert_eq!(
                got_as_json.get(ch),
                Some(&expected),
                "escapes for {ch:?} in {literal:?}"
            );
        }

        // Apply to the decoded body, compare to flynt's applied output.
        if let (Some(decoded), Some(applied)) =
            (entry["decoded"].as_str(), entry["applied"].as_str())
        {
            let got = apply_unicode_escape_map(decoded, got_map);
            assert_eq!(got, applied, "apply for {literal:?}");
        }
    }
}
