//! Differential tests for the `.format()` pipeline (task #6): the Rust port must
//! reproduce flynt 1.0.6's `transform_chunk` and `call_candidates` byte-for-byte.
//!
//! Fixtures are generated by `tests/fixtures/gen_format_fixtures.py` against
//! flynt itself + the integration corpus. `transform_chunk` is exercised on the
//! *bare expression node* (how `CodeEditor` invokes it in the real pipeline).

use std::path::PathBuf;

use flynt_rs::astutils::{ast_to_string, parse_expr};
use flynt_rs::candidates::call::call_candidates;
use flynt_rs::quotes::QuoteType;
use flynt_rs::state::State;
use flynt_rs::transform::transform_chunk;
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap()
}

fn quote_from_name(name: &str) -> QuoteType {
    match name {
        "single" => QuoteType::Single,
        "double" => QuoteType::Double,
        "triple_single" => QuoteType::TripleSingle,
        "triple_double" => QuoteType::TripleDouble,
        other => panic!("unknown quote name {other}"),
    }
}

/// The full `transform_chunk` contract: result string, changed flag, and every
/// state counter, across all four quote types and both aggressive levels.
#[test]
fn format_transform_matches_flynt() {
    let data = fixture("format_transform.json");
    let entries = data.as_array().unwrap();
    let mut failures = Vec::new();
    let mut n = 0usize;

    for entry in entries {
        let code = entry["code"].as_str().unwrap();
        let qt = quote_from_name(entry["quote_type"].as_str().unwrap());
        let aggressive = entry["aggressive"].as_u64().unwrap() as u8;
        let want_changed = entry["changed"].as_bool().unwrap();
        // Python `result` is None when not changed; our port returns "".
        let want_result = entry["result"].as_str().unwrap_or("");
        let want = &entry["counters"];

        let node = match parse_expr(code) {
            Ok(nd) => nd,
            Err(e) => {
                failures.push(format!("PARSE {code:?}: {e}"));
                continue;
            }
        };

        let mut state = State {
            aggressive,
            ..State::default()
        };
        let (got_result, got_changed) = transform_chunk(&node, &mut state, qt);

        let mut problems = Vec::new();
        if got_changed != want_changed {
            problems.push(format!("changed {got_changed} != {want_changed}"));
        }
        if got_result != want_result {
            problems.push(format!("result {got_result:?} != {want_result:?}"));
        }
        for (field, actual) in [
            ("call_candidates", state.call_candidates),
            ("call_transforms", state.call_transforms),
            ("percent_candidates", state.percent_candidates),
            ("percent_transforms", state.percent_transforms),
            ("invalid_conversions", state.invalid_conversions),
        ] {
            let expected = want[field].as_u64().unwrap() as usize;
            if actual != expected {
                problems.push(format!("{field} {actual} != {expected}"));
            }
        }
        if !problems.is_empty() {
            failures.push(format!(
                "code={code:?} qt={qt:?} aggr={aggressive}:\n    {}",
                problems.join("\n    ")
            ));
        }
        n += 1;
    }

    assert!(
        failures.is_empty(),
        "{} / {} transform_chunk mismatches:\n{}",
        failures.len(),
        n,
        failures.join("\n")
    );
    assert!(n > 200, "expected a substantial corpus, got {n}");
}

/// `call_candidates` discovery: the count credited to state and the set of
/// candidate expressions (in source order) must match flynt.
#[test]
fn call_candidates_matches_flynt() {
    let data = fixture("call_candidates.json");
    let mut failures = Vec::new();
    for entry in data.as_array().unwrap() {
        let code = entry["code"].as_str().unwrap();
        let want_count = entry["count"].as_u64().unwrap() as usize;
        let want: Vec<&str> = entry["candidates"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();

        let mut state = State::default();
        let chunks = call_candidates(code, &mut state);
        let got: Vec<String> = chunks
            .iter()
            .map(|c| ast_to_string(&c.node).unwrap())
            .collect();

        if state.call_candidates != want_count {
            failures.push(format!(
                "code={code:?}: count {} != {want_count}",
                state.call_candidates
            ));
        }
        if got != want {
            failures.push(format!("code={code:?}: candidates {got:?} != {want:?}"));
        }
    }
    assert!(
        failures.is_empty(),
        "call_candidates mismatches:\n{}",
        failures.join("\n")
    );
}
