//! Differential tests for the percent pipeline (task #5): the Rust port must
//! reproduce flynt 1.0.6's `transform_binop` + `fixup_transformed` byte-for-byte
//! and `percent_candidates` counts across the integration corpus.
//!
//! Fixtures are generated by `tests/fixtures/gen_percent_fixtures.py`.

use std::path::PathBuf;

use flynt_rs::astutils::{fixup_transformed, parse_expr};
use flynt_rs::candidates::percent::percent_candidates;
use flynt_rs::error::FlyntError;
use flynt_rs::state::State;
use flynt_rs::transform::percent::transform_binop;
use serde_json::Value;

fn fixture() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/percent.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap()
}

/// Full pipeline: `transform_binop` then `fixup_transformed` (default quotes),
/// matching how the fixtures were produced.
fn run(src: &str, aggressive: u8) -> Result<String, FlyntError> {
    let node = parse_expr(src).map_err(|e| FlyntError::Generic(format!("parse {src:?}: {e}")))?;
    let mut state = State::default();
    state.aggressive = aggressive;
    let result = transform_binop(&node, &state)?;
    fixup_transformed(result, None)
}

#[test]
fn transform_matches_flynt() {
    let data = fixture();
    let entries = data["transform"].as_array().unwrap();
    let mut n = 0;
    for entry in entries {
        let src = entry["src"].as_str().unwrap();
        let aggressive = entry["aggressive"].as_u64().unwrap() as u8;
        let kind = entry["kind"].as_str().unwrap();
        let got = run(src, aggressive);
        match kind {
            "ok" => {
                let expected = entry["result"].as_str().unwrap();
                match got {
                    Ok(s) => assert_eq!(s, expected, "transform({src:?}, a={aggressive})"),
                    Err(e) => panic!("transform({src:?}, a={aggressive}) expected Ok({expected:?}), got Err({e})"),
                }
            }
            "refused" => {
                let expected_msg = entry["message"].as_str().unwrap();
                match got {
                    Err(FlyntError::ConversionRefused(m)) => assert_eq!(
                        m, expected_msg,
                        "refusal message for ({src:?}, a={aggressive})"
                    ),
                    other => panic!(
                        "transform({src:?}, a={aggressive}) expected ConversionRefused({expected_msg:?}), got {other:?}"
                    ),
                }
            }
            "error" => {
                // Ordinary exception (KeyError/FlyntException/ValueError): the
                // Rust pipeline must fail, but *not* as a ConversionRefused.
                match got {
                    Err(FlyntError::ConversionRefused(m)) => panic!(
                        "transform({src:?}, a={aggressive}) expected an ordinary error, got ConversionRefused({m:?})"
                    ),
                    Err(_) => {}
                    Ok(s) => panic!(
                        "transform({src:?}, a={aggressive}) expected an error, got Ok({s:?})"
                    ),
                }
            }
            other => panic!("unknown kind {other}"),
        }
        n += 1;
    }
    assert!(n > 100, "expected a substantial transform corpus, got {n}");
}

#[test]
fn candidate_counts_match_flynt() {
    let data = fixture();
    let entries = data["candidates"].as_array().unwrap();
    let mut n = 0;
    for entry in entries {
        let code = entry["code"].as_str().unwrap();
        let expected = entry["count"].as_u64().unwrap() as usize;
        let mut state = State::default();
        let got = percent_candidates(code, &mut state).len();
        assert_eq!(got, expected, "percent_candidates count for {code:?}");
        // The returned length must also equal the state increment.
        assert_eq!(state.percent_candidates, expected, "state increment for {code:?}");
        n += 1;
    }
    assert!(n > 50, "expected a substantial candidate corpus, got {n}");
}
